[build-system]
requires = ["setuptools>=61.0", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "pyprojinit"
version = "0.1.0"
description = "pyprojinit — scaffold Python projects (CLI)"
readme = "README.md"
readme-content-type = "text/markdown"
authors = [ { name = "Your Name", email = "you@example.com" } ]
license = { text = "MIT" }
keywords = ["scaffold", "cookiecutter", "cli", "python"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = []

[project.scripts]
pyprojinit = "pyprojinit:main"